{{- if .Values.forge.localPostgresql }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowforge-database-policy
  labels:
  {{- include "forge.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "forge.forgeSelectorLabels" . | nindent 12 }}
      - podSelector:
          matchLabels:
            {{- include "forge.fileStoreSelectorLabels" . | nindent 12 }}
{{- end }}
