{{- range $name, $policy := .Values.networkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ tpl $name $ }}
  namespace: {{ tpl ($policy.namespace | default $.Release.Namespace) $ }}
  labels:
    {{- include "forge.labels" $ | nindent 4 }}
    {{- with $policy.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with $policy.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- tpl (toYaml $policy.spec) $ | nindent 4 }}
{{- end }}
