forge:
  dbUsername: forge
  dbPassword: Zai1Wied
  dbName: flowforge
  localPostgresql: true
  https: true
  projectNamespace: flowforge
  projectSelector:
    role: projects
  projectDeploymentTolerations: []
  #    - key: purpose
  #      operator: Equal
  #      value: flowforge-projects
  #      effect: NoSchedule
  managementSelector:
    role: management
  telemetry:
    enabled: true
  broker:
    enabled: false
  fileStore:
    enabled: false
    type: localfs
    quota: 104857600
    options:
      root: var/root
    context:
      type: sequelize
      quota: 1048576
      options:
        type: postgres
        host: flowforge-postgresql
        username: forge
        password: ""
        database: ff-context
  support:
    enabled: false

  rate_limits:
    enabled: false
    global: true
    max: 1000
    timeWindow: 60000

  domain: ""
  entryPoint: ""
  environment: {}
  image: ""
  registry: ""

postgresql:
  postgresqlPostgresPassword: Moomiet0
  postgresqlUsername: forge
  postgresqlPassword: Zai1Wied
  postgresqlDatabase: flowforge
  global:
    storageClass: default

ingress:
  annotations: {}
  className: ""

editors:
  serviceAccount:
    create: true
    annotations: {}
    name: editors