forge:
  dbUsername: forge
  dbPassword: ""
  dbName: flowforge
  localPostgresql: true
  https: true
  projectNamespace: flowforge
  projectSelector:
    role: projects
  projectDeploymentTolerations: []
  #    - key: purpose
  #      operator: Equal
  #      value: flowforge-projects
  #      effect: NoSchedule
  managementSelector:
    role: management
  telemetry:
    enabled: true
  broker:
    enabled: false
  fileStore:
    enabled: false
    type: localfs
    quota: 104857600
    options:
      root: var/root
    context:
      type: sequelize
      quota: 1048576
      options:
        type: postgres
        host: flowforge-postgresql
        username: forge
        password: ""
        database: ff-context
  support:
    enabled: false

  domain: ""
  entryPoint: ""
  environment: {}
  image: 355908013639.dkr.ecr.eu-west-1.amazonaws.com/flowforge/forge-k8s:1.5.0
  registry: 355908013639.dkr.ecr.eu-west-1.amazonaws.com

postgresql:
  postgresqlDatabase: flowforge
  postgresqlPassword: ""
  postgresqlPostgresPassword: ""
  postgresqlUsername: forge
  global:
    storageClass: default

ingress:
  annotations: {}
  className: ""

editors:
  serviceAccount:
    create: true
    annotations: {}
    name: editors
    namespace: