{{- if .Values.forge.fileStore.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- .Values.forge.fileStore.serviceAccount.name }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
  {{- with .Values.forge.fileStore.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
{{- end }}
