{{- if and .Values.forge.fileStore.context .Values.forge.localPostgresql -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade.sh
data:
  upgrade.sh: |
    #!/bin/sh
    apk add --no-cache postgresql14-client
    psql -v ON_ERROR_STOP=1 -h {{ .Release.Name }}-postgresql -U postgres postgres <<-ESQL
    SELECT datname FROM pg_database WHERE datistemplate = false;
    SELECT 'CREATE DATABASE "ff-context"' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ff-context')\gexec
    GRANT ALL PRIVILEGES ON DATABASE "ff-context" TO "forge";
    ESQL
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-upgrade
  labels:
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name:
      labels:
        app: flowforge-file
    spec:
      restartPolicy: Never
      containers:
      - name: add-context-db
        image: "alpine:3.17.0"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password
        volumeMounts:
        - name: upgrade-script
          mountPath: /usr/local
        command:
        - /bin/sh
        - /usr/local/upgrade.sh
      volumes:
      - name: upgrade-script
        configMap:
          name: upgrade.sh
{{- end -}}