{{- if not .Values.forge.localPostgresql }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: {{ .Release.Name }}-postgresql
spec:
  externalName: {{ .Values.forge.postgres.host }}
  type: ExternalName
status:
  loadBalancer: {}
---
{{- if .Values.forge.cloudProvider }}
{{- if eq .Values.forge.cloudProvider "aws" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowforge-database-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      nodered: "true"
      role: projects
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/24
{{- end }}
{{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowforge-database-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: flowforge
      - podSelector:
          matchLabels:
            app: flowforge-file
{{- end }}
