{{- if not .Values.forge.localPostgresql }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: {{ .Release.Name }}-postgresql
spec:
  externalName: {{ .Values.forge.postgres.host }}
  type: ExternalName
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowforge-database-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      nodered: "true"
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/24
{{- else }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowforge-database-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
    from:
    -podSelector:
      matchLabels:
        app: flowforge
{{- end }}