{{- if (((.Values.forge).projectNetworkPolicy).enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowfuse-projects-policy
  namespace: {{ .Values.forge.projectNamespace }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    {{- with .Values.forge.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  policyTypes:
    {{- if .Values.forge.projectNetworkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.forge.projectNetworkPolicy.egress }}
    - Egress
    {{- end }}
  podSelector:
    matchLabels:
      nodered: true
  {{- if .Values.forge.projectNetworkPolicy.egress }}
  egress:
    {{- with .Values.forge.projectNetworkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.forge.projectNetworkPolicy.ingress }}
  ingress:
    {{- with .Values.forge.projectNetworkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
