apiVersion: v1
kind: Secret
metadata:
  name: flowfuse-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
