apiVersion: v1
kind: Service
metadata:
  name: forge
spec:
  selector:
    app: flowforge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress
  annotations:
  {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.forge.entryPoint }}
  - host: {{ .Values.forge.entryPoint }}
  {{- else }}
  - host: forge.{{ .Values.forge.domain}}
  {{- end }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: forge
            port:
              number: 80
  {{- if .Values.forge.https }}
  tls:
  - hosts:
    - {{ .Values.forge.entryPoint }}
    {{- if .Values.forge.tlsSecretName }}
    secretName: {{ .Values.forge.tlsSecretName }}
    {{- end }}
  {{- end }}
  