apiVersion: v1
kind: Service
metadata:
  name: forge
spec:
  selector:
    app: flowforge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress
  annotations:
spec:
  rules:
  {{- if .Values.forge.entryPoint }}
  - host: {{ .Values.forge.entryPoint }}
  {{- else }}
  - host: forge.{{ .Values.forge.domain}}
  {{- end }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: forge
            port:
              number: 80
