apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowforge
  {{- if .Values.forge.IAMRole }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.forge.IAMRole | quote }}
    eks.amazonaws.com/sts-regional-endpoints: true
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-pod
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "pods/status"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"] 
# - apiGroups: [""]
#   resources: ["persistentvolumes", "persistentvolumeclaims"]
#   verbs: ["create", "patch", "get", "list", "watch", "delete"] 
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pod
  namespace: flowforge
subjects:
- kind: ServiceAccount
  name: flowforge
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: create-pod
  apiGroup: rbac.authorization.k8s.io
