{{- $forgeHostname := or (.Values.forge.entryPoint) (printf "%s%s" "forge." .Values.forge.domain) -}}
apiVersion: v1
kind: Service
metadata:
  name: forge
spec:
  selector:
    app: flowforge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress
  annotations:
  {{- if .Values.ingress.certManagerIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.certManagerIssuer }}
  {{- end }}
  {{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations |  replace "{{ instanceHost }}" $forgeHostname | replace "{{ serviceName }}" "forge" | indent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ $forgeHostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: forge
            port:
              number: 80
  {{- if .Values.ingress.certManagerIssuer }}
  tls:
  - hosts:
    - {{ $forgeHostname }}
    secretName: {{ $forgeHostname }}
  {{- end }}
