apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowforge
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
  {{- if .Values.forge.cloudProvider }}
  {{- if eq .Values.forge.cloudProvider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.forge.aws.IAMRole | quote }}
    eks.amazonaws.com/sts-regional-endpoints: "true"
  {{- end }}
  {{- end }}


{{- if .Values.editors.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.editors.serviceAccount.name }}
  namespace: {{ .Values.forge.projectNamespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
  {{- with .Values.editors.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ ((.Values.forge).clusterRole).name | default "create-pod" }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "pods/status"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"] 
- apiGroups: ["apps"]
  resources: ["deployments", "deployment/status"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"] 
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ ((.Values.forge).clusterRole).name | default "create-pod" }}
  namespace: {{ .Values.forge.projectNamespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: flowforge
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ ((.Values.forge).clusterRole).name | default "create-pod" }}
  apiGroup: rbac.authorization.k8s.io
