{{- $forgeHostname := or (.Values.forge.entryPoint) (printf "%s%s" "forge." .Values.forge.domain) -}}
apiVersion: v1
kind: Service
metadata:
  name: forge
spec:
  selector:
    app: flowforge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $keys, $values := .Values.ingress.annotations }}
    {{ $keys }}: {{ $values |  replace "{{ instanceHost }}" $forgeHostname | replace "{{ serviceName }}" "forge"}}
    {{- end }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ $forgeHostname}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: forge
            port:
              number: 80
