apiVersion: "v2"
name: "flowfuse"
version: "2.29.0"
description: "FlowFuse"
type: "application"
home: "https://flowfuse.com"
icon: "https://flowfuse.com/apple-touch-icon.png"
keywords:
  - flowfuse
  - node-red
dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: forge.localPostgresql
    import-values:
      - child: image
        parent: postgresql.image
  - name: valkey
    version: 0.4.1
    repository: oci://registry-1.docker.io/cloudpirates
    condition: forge.localValey
maintainers:
  - name: "FlowFuse Inc"
    url: "https://flowfuse.com"
appVersion: "2.22.0"
