name: Release container images
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

env:
  AWS_ECR_ROLE_NAME: "ECR_push_pull_images"
  AWS_ECR_REGION: "eu-west-1"
  AWS_ECR_NODE_RED_REPOSITORY_NAME: "flowforge/node-red"

jobs:
  build_application_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'
      # sets options for Docker build
      # will tag contianers with ${{ github.event.inputs.version }} and latest
      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ github.event.inputs.version }}
          flavor: |
            latest=true
          images: |
            flowforge/forge-k8s
            flowfuse/forge-k8s
      # sets up multi platform emulators
      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      # sets up docker buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      # logs into docker hub
      - name: docker login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # builds container
      - name: Build and push FlowForge Application container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/flowforge-container
          file: helm/flowforge-container/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
      - name: Push README
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowforge/forge-k8s
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          readme-filepath: ./helm/flowforge-container/README.md
      - name: Push README flowfuse
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowfuse/forge-k8s
          username: flowfuse
          password: ${{ secrets.DOCKER_HUB_PASSWORD_FLOWFUSE }}
          readme-filepath: ./helm/flowforge-container/README.md

  build_nodered_container:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_ECR_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          role-session-name: GithubActionsRoleSession
          role-duration-seconds: 900
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: "${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}"

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ github.event.inputs.version }}
            type=raw,enable=true,priority=200,prefix=latest-,suffix=,value=3.0.x
          flavor: |
            latest=false
          images: |
            flowforge/node-red
            flowfuse/node-red
            ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_NODE_RED_REPOSITORY_NAME }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
  
      - name: Build and push Node-RED container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/node-red-container
          file: helm/node-red-container/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Push README
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowforge/node-red
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          readme-filepath: ./helm/node-red-container/README.md

      - name: Push README flowfuse
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowfuse/node-red
          username: flowfuse
          password: ${{ secrets.DOCKER_HUB_PASSWORD_FLOWFUSE }}
          readme-filepath: ./helm/node-red-container/README.md

  build_nodered_container_223:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_ECR_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          role-session-name: GithubActionsRoleSession
          role-duration-seconds: 900
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: "${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}"

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=-2.2.3,value=${{ github.event.inputs.version }}
            type=raw,enable=true,priority=200,prefix=latest-,suffix=,value=2.2.x
          flavor: |
            latest=false
          images: |
            flowforge/node-red
            flowfuse/node-red
            ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_NODE_RED_REPOSITORY_NAME }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push Node-RED container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/node-red-container
          file: helm/node-red-container/Dockerfile-2.2.x
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  build_nodered_container_31:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_ECR_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          role-session-name: GithubActionsRoleSession
          role-duration-seconds: 900
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: "${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}"

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=-3.1.x,value=${{ github.event.inputs.version }}
            type=raw,enable=true,priority=200,prefix=latest-,suffix=,value=3.1.x
          flavor: |
            latest=false
          images: |
            flowforge/node-red
            flowfuse/node-red
            ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_NODE_RED_REPOSITORY_NAME }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push Node-RED container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/node-red-container
          file: helm/node-red-container/Dockerfile-3.1
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  build_nodered_container_40:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_ECR_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          role-session-name: GithubActionsRoleSession
          role-duration-seconds: 900
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: "${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}"

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=-4.0.x,value=${{ github.event.inputs.version }}
            type=raw,enable=true,priority=200,prefix=latest-,suffix=,value=4.0.x
          flavor: |
            latest=false
          images: |
            flowforge/node-red
            flowfuse/node-red
            ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_NODE_RED_REPOSITORY_NAME }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push Node-RED container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/node-red-container
          file: helm/node-red-container/Dockerfile-4.0
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  build_nodered_container_41:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_ECR_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          role-session-name: GithubActionsRoleSession
          role-duration-seconds: 900
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: "${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}"

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=-4.1.x,value=${{ github.event.inputs.version }}
            type=raw,enable=true,priority=200,prefix=latest-,suffix=,value=4.1.x
          flavor: |
            latest=true
          images: |
            flowforge/node-red
            flowfuse/node-red
            ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_NODE_RED_REPOSITORY_NAME }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push Node-RED container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/node-red-container
          file: helm/node-red-container/Dockerfile-4.1
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  build_file_server_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'
      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ github.event.inputs.version }}
          flavor: |
            latest=true
          images: |
            flowforge/file-server
            flowfuse/file-server
      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: docker login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push FlowForge File Server container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/file-server
          file: helm/file-server/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
      - name: Push README
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowforge/file-server
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          readme-filepath: ./helm/file-server/README.md
      - name: Push README flowfuse
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowfuse/file-server
          username: flowfuse
          password: ${{ secrets.DOCKER_HUB_PASSWORD_FLOWFUSE }}
          readme-filepath: ./helm/file-server/README.md

  build_nodered_container_50:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowfuse/helm'
          path: 'helm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_ECR_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          role-session-name: GithubActionsRoleSession
          role-duration-seconds: 900
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: "${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}"

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=-5.0.x,value=${{ github.event.inputs.version }}
            type=raw,enable=true,priority=200,prefix=latest-,suffix=,value=5.0.x
          flavor: |
            latest=false
          images: |
            flowforge/node-red
            flowfuse/node-red
            ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_NODE_RED_REPOSITORY_NAME }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push Node-RED container
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: helm/node-red-container
          file: helm/node-red-container/Dockerfile-5.0
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
