name: Debug image pull from ghcr.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pull:
    name: Pull image
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - name: Login to temporary registry
        id: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pull temporary image"
        run: |
          docker pull ghcr.io/flowforge/file-server:main
