name: Build Flowforge container

on:
  workflow_dispatch:
    inputs:
      flowforge_release_name:
        description: 'flowforge package version'
        required: false
        default: 'nightly'
      flowforge_ref:
        description: 'flowforge package ref'
        required: false
  schedule:
    - cron: '30 5 * * *'
  push:
    branches:
      - 'feat-*'
  pull_request:
    branches:
      - main

jobs:
  build-stage:
    if: true
    uses: flowforge/github-actions-workflows/.github/workflows/build_container_image.yml@feat-container-build
    with:
      environment: 'stage'
      image_name: 'forge-k8s'
      package_dependencies: |
        @flowforge/flowforge
        @flowforge/kubernetes
      build_context: 'flowforge-container'
      npm_registry_url: ${{ vars.PRIVATE_NPM_REGISTRY_URL }}
    secrets:
      npm_registry_auth_token: ${{ secrets.GITHUB_TOKEN }}

  dispatch:
    runs-on: ubuntu-latest
    needs: [build-stage]
    if: false
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}

      - name: Trigger cloud deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          repo: flowforge/CloudProject
          ref: feat-deployment-poc
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"flowforge_image_tag": "${{ env.image_tag }}"}'
  