name: Flowforge - build and deploy
on:
  workflow_dispatch:
    inputs:
      flowforge_release_name:
        description: 'flowforge package version'
        required: false
        default: 'nightly'
      flowforge_ref:
        description: 'flowforge package ref'
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build single-architecture container images
    uses: flowforge/github-actions-workflows/.github/workflows/build_container_image.yml@cc8efbe5e4897e997d3b170a970a1afca9410273
    with:
      image_name: 'forge-k8s'
      package_dependencies: |
        @flowforge/flowforge
        @flowforge/kubernetes
      build_context: 'flowforge-container'
      npm_registry_url: ${{ vars.PUBLIC_NPM_REGISTRY_URL }}
    secrets:
      npm_registry_auth_token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      temporary_registry_token: ${{ secrets.GITHUB_TOKEN }}

  build-multi-architecture:
    name: Build multi-architecture container image
    needs: build
    uses: flowforge/github-actions-workflows/.github/workflows/merge_multiarch_images.yml@cc8efbe5e4897e997d3b170a970a1afca9410273
    with:
      image_name: 'forge-k8s'
    secrets:
      temporary_registry_token: ${{ secrets.GITHUB_TOKEN }}
  
  deploy-stage:
    name: Deploy to staging environment
    needs: build-multi-architecture
    uses: flowforge/github-actions-workflows/.github/workflows/deploy_container_image.yml@cc8efbe5e4897e997d3b170a970a1afca9410273
    with:
      environment: stage
      service_name: 'forge-k8s'
      deployment_name: flowforge
      container_name: forge
      image: ${{ needs.build-multi-architecture.outputs.image }}
    secrets:
      aws_access_key_id: ${{ secrets.STAGING_AWS_ID }}
      aws_secret_access_key: ${{ secrets.STAGING_AWS_KEY }}
      temporary_registry_token: ${{ secrets.GITHUB_TOKEN }}
      eks_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}
  
  deploy-prod:
    if: github.ref_name == 'main'
    name: Deploy to production environment
    needs: [build-multi-architecture, deploy-stage]
    uses: flowforge/github-actions-workflows/.github/workflows/deploy_container_image.yml@cc8efbe5e4897e997d3b170a970a1afca9410273
    with:
      environment: production
      service_name: 'forge-k8s'
      deployment_name: flowforge
      container_name: forge
      image: ${{ needs.build-multi-architecture.outputs.image }}
    secrets:
      aws_access_key_id: ${{ secrets.PRODUCTION_AWS_ID }}
      aws_secret_access_key: ${{ secrets.PRODUCTION_AWS_KEY }}
      temporary_registry_token: ${{ secrets.GITHUB_TOKEN }}
      eks_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}
