name: Build Flowforge container
on:
  workflow_dispatch:
    inputs:
      flowforge_release_name:
        description: 'flowforge package version'
        required: false
        default: 'nightly'
      flowforge_ref:
        description: 'flowforge package ref'
        required: false
  schedule:
    - cron: '30 5 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-stage:
    uses: flowforge/github-actions-workflows/.github/workflows/build_container_image.yml@main
    with:
      environment: 'stage'
      image_name: 'forge-k8s'
      package_dependencies: |
        @flowforge/flowforge
        @flowforge/kubernetes
      build_context: 'flowforge-container'
      npm_registry_url: ${{ vars.PRIVATE_NPM_REGISTRY_URL }}
    secrets:
      npm_registry_auth_token: ${{ secrets.GITHUB_TOKEN }}
      aws_access_key_id: ${{ secrets.STAGING_AWS_ID }}
      aws_access_key_secret: ${{ secrets.STAGING_AWS_KEY }}
  